[package]
name = "pokeviewerctl"
description = "Linux USB provisioning and diagnostics CLI for Pokeviewer"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
jiff = { version = "=0.2.35", default-features = true }
pokeviewer-core = { path = "../pokeviewer-core" }
serial2 = { version = "=0.2.37", default-features = false }

[dev-dependencies]
serial2 = { version = "=0.2.37", default-features = false, features = ["unix"] }

[lints]
workspace = true
