[package]
name = "pokeviewer-firmware"
description = "Board-specific no_std firmware for Pokeviewer"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
embedded-hal = { version = "=1.0.0", default-features = false }
embedded-hal-async = { version = "=1.0.0", default-features = false }
pcf85063a = { version = "=0.1.1", default-features = false }
pokeviewer-core = { version = "=1.1.0", path = "../pokeviewer-core" }
time = { version = "=0.3.54", default-features = false }

[target.'cfg(target_arch = "xtensa")'.dependencies]
epd-waveshare = { version = "=0.6.0", default-features = false, features = ["epd2in13_v3", "graphics"] }
embedded-graphics = { version = "=0.8.2", default-features = false }
embedded-hal-bus = { version = "=0.3.0", default-features = false }
embassy-futures = { version = "=0.1.2", default-features = false }
esp-backtrace = { version = "=0.19.0", git = "https://github.com/esp-rs/esp-hal", rev = "434755e0447fc1a4ba30fd84da3cf746ec082e00", default-features = false, features = ["esp32s3", "panic-handler", "println"] }
esp-bootloader-esp-idf = { version = "=0.5.0", git = "https://github.com/esp-rs/esp-hal", rev = "434755e0447fc1a4ba30fd84da3cf746ec082e00", default-features = false, features = ["esp32s3"] }
esp-hal = { version = "=1.1.0", git = "https://github.com/esp-rs/esp-hal", rev = "434755e0447fc1a4ba30fd84da3cf746ec082e00", default-features = false, features = ["esp32s3", "exception-handler", "float-save-restore", "rt", "unstable"] }
esp-println = { version = "=0.17.0", git = "https://github.com/esp-rs/esp-hal", rev = "434755e0447fc1a4ba30fd84da3cf746ec082e00", default-features = false, features = ["esp32s3", "jtag-serial"] }
pokeviewer-esp32s3-pad-hold = { version = "=1.1.0", path = "../pokeviewer-esp32s3-pad-hold" }
portable-atomic = { version = "=1.14.0", default-features = false }

[[bin]]
name = "pokeviewer-firmware"
path = "src/main.rs"
bench = false
test = false

[lints]
workspace = true
